# startup.cmd -m standalone 单节点启动nacos
spring:
  application:
    name: seata-demo1-bank1


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alibaba:
      seata:
        # 覆盖名称，默认为 ${spring.application.name}-fescar-service-group
        # 覆盖之后，file.conf也要进行覆盖
        tx-service-group: seata-demo1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_bank1?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root


logging:
  level:
    root: INFO
    com:
      zt: DEBUG
      alibaba: ERROR


server:
  port: 8083
feign:
  client:
    config:
      default:
        #超时时间默认为1s
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 15000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 15000
