server:
  port: 8091
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis_study?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 192.168.6.241
    port: 6379
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
    database: 2
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.zt.entity # 别名扫描包
logging:
  level:
    com.zt: debug